import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import ReactQueryProvider from "@/providers/react-query";
import Footer from "@/components/Footer/Footer";
import HeaderBottom from "@/components/HeaderBottom/Bottom";
import Providers from "@/providers/session";



export const metadata: Metadata = {
  title: "Лучшие запчасти",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="wrapper">
        <Providers>
          <ReactQueryProvider>
            <Header />
            <HeaderBottom />
            <main>{children}</main>
            <Footer />
          </ReactQueryProvider>
        </Providers>
        
      </body>
    </html>
  );
}
